services:
  postgres:
    image: postgres:10
    container_name: demo-app-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    build: 
      context: ./spring-boot-app
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./spring-boot-app/spring-boot-conf.yml:/app/config/spring-boot-conf.yml

  node-app:
    build: 
      context: ./node-app
      dockerfile: Dockerfile
    depends_on:
      - spring-boot-app
    ports:
      - "8081:8081"
    environment:
      SPRING_BOOT_URL: http://spring-boot-app:8080

volumes:
  postgres_data: